Support importing cookies.txt to workaround infinite challenge requests
instaloader/instaloader pull request #877
Opened 2020-11-17 17:41 UTC by elexis1

Same issue as described in the following issues:

#92
#217
#615 

When using instaloader, it asks for a challenge performed in the browser:
> Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/xxx/yyy/, follow the instructions, then retry.

Been there, done that, only result is that you just get another challenge, forever.

There are code snippet shareds in the issues, and committed in 27b7c98be2beaf8af899d53e7ab30c373872a598 (see  #615).

It loads the Firefox "cookies.sqlite" and writes a new instaloader session file.

However, this snippet doesn't work anymore, because Firefox uses an **exclusive lock**.
Hence sqlite3 cannot read from `cookies.sqlite`, and the script can't function.
For example running `sqlite3 ~/.mozilla/firefox/*/cookies.sqlite` and `SELECT name, value FROM moz_cookies;`.
See also:
https://superuser.com/questions/635317/sqlite-database-browser-fails-to-open-firefox-cookie-database
https://www.sqlite.org/pragma.html#pragma_locking_mode

I'm using Firefox 82.0.3, the lock was introduced probably 

To work around this issue, I have adapted the script to work with `cookies.txt` files.

To obtain the cookies.txt from Firefox, one can install a plugin, such as this https://addons.mozilla.org/de/firefox/addon/export-cookies-txt/

This is a severe issue because it makes it impossible to use the program for me.

2020-11-21 12:06 UTC, aandergr commented
> However, this snippet doesn't work anymore, because Firefox uses an **exclusive lock**.
> Hence sqlite3 cannot read from `cookies.sqlite`, and the script can't function.
>
> [...]
> 
> This is a severe issue for the people affected by the infinite challenge loop, because it makes it impossible to use the program for them.

That is not true. Firefox can only hold the lock while it is running. Calling the snippet while Firefox  is running results in the message _Cookie import failed: database is locked_. The snippet works fine when no Firefox instance is running.

2020-11-22 22:57 UTC, elexis1 commented
Yes, the lock should be gone if firefox is closed.

At the very least the instructions are incomplete:
> #. Login to Instagram in Firefox,
> #. Execute the snippet, e.g. with ``python 615_import_firefox_session.py``,

I don't know how many people store their cookies across browser sessions or what the defaults are.
People who delete cookies upon closing the browser would have to get the hassle to:
- disable deletion of cookies
-  shutting down firefox, which kills all active sessions, possibly open forms data, selected text, the location of each page one scrolled in
- has to reload all tabs again (for some the content might have changed)
- change the settings again to delete cookies upon quit.

That hassle is multiplied everytime one gets into this verification loop.

So to me those 3 lines of code load the cookies file from a cookies.txt instead of the cookie.sqlite file not only make it much easier but make it feasible at all for me. I'd have to keep this script around merely to keep firefox settings and be able to use instaloader.

Judging by that, there are two things we observe:
- The lockout loop shouldn't be a thing that happens to begin with. The challenge should be solved once and then it should be fine instead of loop forever. So the real question is why is there a challenge loop and how can it be avoided without a manual cookie extraction with a script.

- If the challenge loop can't be fixed for good, perhaps it would be cleaner to not use one or two code snippets for the needy but to integrate it into instaloader as a commandline argument `--cookies cookiefile`. Perhaps that could support both txt and sqlite format (either by two arguments or content type detection).

2020-11-23 17:25 UTC, aandergr commented
Ah that's right. I'm sorry, I hadn't thought about it in enough detail on Saturday when I wrote my comment, what consequences it can actually have for a user that the script cannot access the cookies while Firefox is running. Thanks for your patience and your explanatory comment!

How about if we just get the script to open the original cookies database even if it is locked? We could do that by passing the [immutable flag](https://www.sqlite.org/uri.html#uriimmutable) to SQLite, since we only access the database read-only:

```diff
--- a/docs/codesnippets/615_import_firefox_session.py
+++ b/docs/codesnippets/615_import_firefox_session.py
@@ -23,7 +23,7 @@ def get_cookiefile():
 
 def import_session(cookiefile, sessionfile):
     print("Using cookies from {}.".format(cookiefile))
-    conn = connect(cookiefile)
+    conn = connect(f"file:{cookiefile}?immutable=1", uri=True)
     try:
         cookie_data = conn.execute(
             "SELECT name, value FROM moz_cookies WHERE baseDomain='instagram.com'"
```

This fixes importing the cookies from Firefox for me, and I think it is easier than taking the workaround via the cookiejar.

2020-11-27 00:02 UTC, elexis1 commented
I can confirm that this avoids running into the lock issue.

However the cookies file does not contain the cookies, because firefox presumably cached them and didn't write it to the cookies.sqlite until having closed firefox, and when closing firefox, the cookies are deleted depending on setting.

Hence the instaloader script tells me I'm not logged in in firefox (but I am).
Equivalently I get an empty table when doing this:
> sqlite3 file:///home/user/.mozilla/firefox/layinfzi.default/cookies.sqlite?immutable=1
> SELECT * FROM moz_cookies;

To ensure that the file isn't broken somehow, I've closed firefox, deleted (renamed) cookies.sqlite, started firefox, logged in, cookies.sqlite was recreated, but still claims an empty table.

I assume that this is because the cookies are cached and the cache is only written to the file on the disk when the buffer is flushed, not everytime a cookie is created. And in the case of sticking with the automatically deleting cookies on exit setting, I suspect there might be no way to flush cookies.sqlite explicitly.
The file modification date does not change when I create more cookies (login elsewhere), even 20 minutes later, until I close firefox.

2020-11-27 10:31 UTC, aandergr requested changes
I see, thanks for experimenting with that! So the issue addressed by adding the cookiejar import script is not that Firefox locks its cookie database, since we can still open it for reading (after a small change that is not committed yet), but that it seems that Firefox under certain (unknown?) conditions or settings does not persist the cookies.

I added a few inline comments in this review, with some (very minor) issues I noticed when going over the changes.

2020-11-27 10:31 UTC, aandergr commented on docs/codesnippets/615_import_firefox_session_sqlite.py
> +#!/usr/local/bin/python3
Could we remove the shebang here? The snippet is included verbatim in the documentation, and this adds two lines without adding any real value, I think.

2020-11-27 10:31 UTC, aandergr commented on docs/troubleshooting.rst
> +If this script doesn't work for you (for example because Firefox locks the sqlite file),
Two ideas here:

- With connecting to the file with immutable=1 (which still has to be changed), Firefox locking the file is not a reason for 615_import_firefox_session.py to not work, so we should choose another example, or remove the "for example" clause.
- Maybe (not so sure about that, just want to suggest it), "If this script doesn't work for you" should be written in bold (surrounded by two asterisks `**`) to be more visible when being frustrated and not reading all the text.

2021-03-20 14:32 UTC, closed without merging